Bootstrap: docker
From: tensorflow/tensorflow:1.13.2-py3

%post
apt-get update && apt-get install -y git
pip install bert-serving-server
git clone https://github.com/hanxiao/bert-as-service /app

%environment
export NUM_WORKER=1

%startscript
bert-serving-start -cpu -num_worker=$NUM_WORKER -model_dir /model
