Bootstrap: docker
From: linuxserver/code-server

%startscript
    printf "Password will be available in ~/.config/code-server/config.yaml.\n"
    printf "Browse to http://127.0.0.1:8443 to open interface\n"
    exec /usr/local/bin/code-server --bind-addr 0.0.0.0:8443
