version: "1.0"
instances:

  db:
    build:
      context: ./db
      recipe: Singularity
    ports:
      - 5432:5432
    volumes:
     - ./db/data:/var/lib/postgresql/data
  uwsgi:
    build:
      context: .
      recipe: Singularity
    volumes:
      - .:/code
      - ./static:/var/www/static
      - ./images:/var/www/images
    post:
      command: ["/bin/bash", "run_post.sh"]
  nginx:               
    build:
      context: ./nginx
      recipe: Singularity
    ports:
      - "80:80"
    volumes:
      - ./nginx/run/nginx.pid:/var/run/nginx.pid
      - ./nginx/cache:/var/cache/nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par
      - ./static:/var/www/static
      - ./images:/var/www/images
